// Sentiment keyword weights — positive values are bullish signals, negative are bearish
export const BULLISH_KEYWORDS = {
  "beats": 3,
  "beat": 3,
  "record": 2,
  "upgrade": 3,
  "upgraded": 3,
  "raised guidance": 3,
  "raises guidance": 3,
  "acquisition": 2,
  "acquires": 2,
  "acquired": 2,
  "partnership": 2,
  "partners with": 2,
  "breakout": 2,
  "exceeds expectations": 3,
  "exceeded expectations": 3,
  "surpasses": 3,
  "surpassed": 3,
  "outperforms": 2,
  "outperformed": 2,
  "profit": 1,
  "revenue growth": 2,
  "revenue beat": 3,
  "earnings beat": 3,
  "eps beat": 3,
  "strong results": 2,
  "buy rating": 3,
  "buy": 1,
  "bullish": 2,
  "rally": 2,
  "rallies": 2,
  "surge": 2,
  "surges": 2,
  "soars": 2,
  "soar": 2,
  "jumps": 2,
  "jump": 2,
  "climbs": 1,
  "gain": 1,
  "gains": 1,
  "growth": 1,
  "expands": 1,
  "expansion": 1,
  "new high": 2,
  "all-time high": 3,
  "dividend increase": 2,
  "buyback": 2,
  "share buyback": 2,
  "stock buyback": 2,
  "positive outlook": 2,
  "raised price target": 3,
  "price target raised": 3,
  "analyst upgrade": 3,
  "strong buy": 3,
  "overweight": 2,
  "outperform": 2
};

export const BEARISH_KEYWORDS = {
  "misses": -3,
  "miss": -3,
  "missed": -3,
  "downgrade": -3,
  "downgraded": -3,
  "recall": -2,
  "layoffs": -2,
  "layoff": -2,
  "sec investigation": -3,
  "sec probe": -3,
  "guidance cut": -3,
  "cuts guidance": -3,
  "cut guidance": -3,
  "lowered guidance": -3,
  "bankruptcy": -4,
  "bankrupt": -4,
  "lawsuit": -2,
  "litigation": -2,
  "investigation": -2,
  "fraud": -3,
  "fine": -2,
  "penalty": -2,
  "earnings miss": -3,
  "revenue miss": -3,
  "eps miss": -3,
  "below expectations": -3,
  "disappoints": -3,
  "disappointing": -2,
  "sell rating": -3,
  "sell": -1,
  "bearish": -2,
  "decline": -2,
  "declines": -2,
  "drops": -2,
  "drop": -2,
  "falls": -2,
  "fall": -2,
  "plunges": -3,
  "plunge": -3,
  "slumps": -2,
  "slump": -2,
  "loss": -2,
  "losses": -2,
  "negative outlook": -2,
  "lowered price target": -3,
  "price target cut": -3,
  "analyst downgrade": -3,
  "underweight": -2,
  "underperform": -2,
  "warning": -1,
  "concern": -1,
  "risk": -1,
  "headwinds": -2,
  "restructuring": -1,
  "write-down": -2,
  "writedown": -2,
  "impairment": -2
};

// Magnitude modifiers that multiply the base keyword weight
export const MAGNITUDE_MODIFIERS = {
  "significantly": 1.5,
  "sharply": 1.5,
  "unexpected": 1.5,
  "unexpectedly": 1.5,
  "dramatically": 1.5,
  "massively": 1.5,
  "huge": 1.4,
  "major": 1.3,
  "strong": 1.3,
  "strongly": 1.3,
  "slight": 0.5,
  "slightly": 0.5,
  "modest": 0.6,
  "modestly": 0.6,
  "small": 0.5
};

// Minimum absolute aggregate score required to emit a signal
export const SIGNAL_THRESHOLD = 2;

// Maximum age of articles to include (72 hours in milliseconds)
export const MAX_ARTICLE_AGE_MS = 72 * 60 * 60 * 1000;

// Alarm name for periodic refresh
export const REFRESH_ALARM_NAME = "finance-signal-refresh";

// How often to refresh news data (in minutes)
export const REFRESH_INTERVAL_MINUTES = 30;

// chrome.storage.local keys
export const STORAGE_KEYS = {
  LATEST_SIGNALS: "latestSignals",
  LATEST_ARTICLES: "latestArticles",
  FEEDBACK_LOG: "feedbackLog",
  LAST_FETCH_TIME: "lastFetchTime"
};

// Known tickers with plain-language company descriptions for users unfamiliar with companies
export const TICKER_TO_COMPANY = {
  "AAPL": "Apple — makes iPhones, MacBooks, and the App Store",
  "MSFT": "Microsoft — makes Windows, Office, and Azure cloud services",
  "GOOGL": "Alphabet / Google — runs the Google search engine, YouTube, and Google Cloud",
  "GOOG": "Alphabet / Google (Class C) — runs the Google search engine, YouTube, and Google Cloud",
  "AMZN": "Amazon — runs the world's largest online store and AWS cloud infrastructure",
  "NVDA": "Nvidia — designs chips (GPUs) used in AI, gaming, and data centers",
  "META": "Meta — owns Facebook, Instagram, and WhatsApp",
  "TSLA": "Tesla — makes electric vehicles and energy storage systems",
  "BRK.A": "Berkshire Hathaway (Class A) — Warren Buffett's holding company owning many large businesses",
  "BRK.B": "Berkshire Hathaway (Class B) — Warren Buffett's holding company owning many large businesses",
  "LLY": "Eli Lilly — pharmaceutical company known for diabetes and weight-loss drugs",
  "V": "Visa — operates the world's largest electronic payment network",
  "JPM": "JPMorgan Chase — the largest US bank by assets",
  "UNH": "UnitedHealth Group — the largest US health insurance company",
  "XOM": "ExxonMobil — one of the world's largest oil and gas companies",
  "JNJ": "Johnson & Johnson — makes pharmaceuticals, medical devices, and consumer products",
  "WMT": "Walmart — the world's largest retailer by revenue",
  "MA": "Mastercard — operates a global electronic payment network",
  "PG": "Procter & Gamble — makes consumer brands like Tide, Pampers, and Gillette",
  "HD": "Home Depot — the largest US home improvement retailer",
  "CVX": "Chevron — major US oil and gas company",
  "MRK": "Merck — pharmaceutical company known for Keytruda cancer drug",
  "ABBV": "AbbVie — pharmaceutical company known for Humira and Botox",
  "KO": "Coca-Cola — the world's largest beverage company",
  "AVGO": "Broadcom — designs semiconductor chips for data centers and networking",
  "PEP": "PepsiCo — makes Pepsi beverages, Lay's chips, and Quaker foods",
  "COST": "Costco — membership-based warehouse retailer",
  "TMO": "Thermo Fisher Scientific — makes instruments and reagents for scientific research",
  "MCD": "McDonald's — the world's largest fast food chain",
  "CSCO": "Cisco Systems — makes networking hardware and software for enterprises",
  "ACN": "Accenture — global consulting and IT services firm",
  "ABT": "Abbott Laboratories — makes medical devices, diagnostics, and nutrition products",
  "DHR": "Danaher — makes precision instruments for life sciences and diagnostics",
  "LIN": "Linde — the world's largest industrial gases company",
  "NKE": "Nike — the world's largest athletic footwear and apparel brand",
  "TXN": "Texas Instruments — makes analog and embedded semiconductors",
  "PM": "Philip Morris International — makes cigarettes and tobacco alternatives globally",
  "VZ": "Verizon — one of the two largest US mobile carriers",
  "DIS": "Walt Disney — owns Disney Parks, ESPN, Pixar, Marvel, and Star Wars",
  "NEE": "NextEra Energy — the world's largest producer of solar and wind energy",
  "MS": "Morgan Stanley — major US investment bank and wealth manager",
  "UNP": "Union Pacific — operates the largest US freight railroad",
  "RTX": "RTX (Raytheon) — makes aerospace and defense systems",
  "HON": "Honeywell — makes industrial automation, aerospace, and building technology",
  "BMY": "Bristol-Myers Squibb — pharmaceutical company making cancer and cardiovascular drugs",
  "QCOM": "Qualcomm — designs chips used in most Android smartphones",
  "AMGN": "Amgen — biotech company making drugs for cancer, bone disease, and inflammation",
  "T": "AT&T — one of the two largest US mobile carriers",
  "INTC": "Intel — largest US maker of PC and server processors",
  "AMD": "AMD — makes CPUs and GPUs competing with Intel and Nvidia",
  "PYPL": "PayPal — runs the PayPal and Venmo digital payment platforms",
  "CRM": "Salesforce — the world's largest customer relationship management software company",
  "NOW": "ServiceNow — makes cloud software for IT and business workflow automation",
  "UBER": "Uber — runs the world's largest ride-sharing and food delivery platforms",
  "ABNB": "Airbnb — operates the world's largest home-sharing rental platform",
  "SNAP": "Snap — makes the Snapchat photo/video messaging app",
  "SPOT": "Spotify — the world's largest music and podcast streaming service",
  "NFLX": "Netflix — the world's largest video streaming service",
  "BA": "Boeing — makes commercial aircraft and defense systems",
  "CAT": "Caterpillar — makes heavy construction and mining equipment",
  "GS": "Goldman Sachs — major US investment bank",
  "BKNG": "Booking Holdings — runs Booking.com, Priceline, and other travel platforms",
  "SBUX": "Starbucks — the world's largest coffeehouse chain",
  "GE": "GE Aerospace — makes jet engines and aviation systems",
  "F": "Ford — major US automaker",
  "GM": "General Motors — major US automaker",
  "PFE": "Pfizer — pharmaceutical company known for COVID vaccines and cancer drugs",
  "AZN": "AstraZeneca — UK-Swedish pharmaceutical company",
  "TSM": "TSMC — the world's largest contract chip manufacturer (makes chips for Apple and Nvidia)",
  "SHOP": "Shopify — e-commerce platform used by small and mid-size businesses",
  "SQ": "Block (formerly Square) — makes payment hardware and the Cash App",
  "COIN": "Coinbase — the largest US cryptocurrency exchange",
  "PLTR": "Palantir — makes data analytics software for governments and enterprises",
  "ARM": "Arm Holdings — designs CPU architectures used in nearly all smartphones",
  "ASML": "ASML — makes the machines that print chips; critical to the semiconductor supply chain",
  "MU": "Micron Technology — makes DRAM and NAND memory chips",
  "WFC": "Wells Fargo — one of the four largest US banks",
  "BAC": "Bank of America — one of the four largest US banks",
  "C": "Citigroup — one of the four largest US banks",
  "BX": "Blackstone — the world's largest alternative asset manager",
  "SPGI": "S&P Global — runs the S&P 500 index and provides financial data",
  "MCO": "Moody's — provides credit ratings and financial intelligence",
  "ICE": "Intercontinental Exchange — operates the New York Stock Exchange",
  "CME": "CME Group — operates the world's largest derivatives exchange",
  "PANW": "Palo Alto Networks — makes enterprise cybersecurity products",
  "CRWD": "CrowdStrike — makes cloud-based endpoint cybersecurity software",
  "SNOW": "Snowflake — makes cloud data warehousing software",
  "DDOG": "Datadog — makes cloud monitoring and observability software",
  "ZM": "Zoom — makes the Zoom video conferencing platform",
  "OKTA": "Okta — makes identity and access management software",
  "NET": "Cloudflare — runs a global content delivery and security network",
  "MDB": "MongoDB — makes a widely used open-source document database",
  "ESTC": "Elastic — makes Elasticsearch, used for search and log analytics",
  "RH": "RH (Restoration Hardware) — luxury home furnishings retailer",
  "LULU": "Lululemon — premium athletic apparel brand",
  "TGT": "Target — major US discount retailer",
  "LOW": "Lowe's — the second-largest US home improvement retailer",
  "DE": "John Deere — makes farm equipment and precision agriculture technology",
  "LMT": "Lockheed Martin — makes F-35 jets and other defense systems",
  "NOC": "Northrop Grumman — makes B-21 bombers and other defense systems",
  "GD": "General Dynamics — makes Gulfstream jets and defense systems",
  "OXY": "Occidental Petroleum — US oil and gas company",
  "COP": "ConocoPhillips — major US oil and gas exploration company",
  "SLB": "SLB (Schlumberger) — the world's largest oilfield services company",
  "HAL": "Halliburton — major oilfield services company",
  "ADP": "ADP — the largest US payroll processing and HR services company",
  "MSTR": "Strategy (MicroStrategy) — software company known for holding large amounts of Bitcoin",
  "GME": "GameStop — US video game retailer known for the 2021 short squeeze",
  "AMC": "AMC Entertainment — the largest US movie theater chain",
  "RIVN": "Rivian — makes electric trucks and SUVs, backed by Amazon",
  "LCID": "Lucid Motors — makes premium electric vehicles",
  "NIO": "NIO — Chinese electric vehicle manufacturer",
  "BIDU": "Baidu — China's largest internet search engine (the 'Google of China')",
  "BABA": "Alibaba — China's largest e-commerce and cloud company",
  "JD": "JD.com — China's second-largest e-commerce company",
  "TCEHY": "Tencent — Chinese tech conglomerate owning WeChat, gaming, and cloud",
  "WMG": "Warner Music Group — one of the three major record labels",
  "SPOT": "Spotify — the world's largest music and podcast streaming service",
  "RBLX": "Roblox — makes the Roblox online game platform popular with children",
  "HOOD": "Robinhood — commission-free stock and crypto trading app",
  "AFRM": "Affirm — buy-now-pay-later lending platform",
  "UPST": "Upstart — AI-powered personal loan platform",
  "SOFI": "SoFi Technologies — online personal finance and banking app",
  "OPEN": "Opendoor — online real estate marketplace for buying and selling homes",
  "DASH": "DoorDash — the largest US food delivery platform",
  "LYFT": "Lyft — the second-largest US ride-sharing platform",
  "PINS": "Pinterest — visual discovery and image sharing social platform",
  "TWTR": "X (formerly Twitter) — microblogging and social media platform",
  "SNAP": "Snap — makes the Snapchat photo/video messaging app",
  "ROKU": "Roku — makes TV streaming devices and an ad-supported streaming platform",
  "TTD": "The Trade Desk — digital advertising technology platform",
  "CELH": "Celsius Holdings — makes Celsius energy drinks",
  "MNST": "Monster Beverage — makes Monster energy drinks",
  "KHC": "Kraft Heinz — makes Kraft mac and cheese, Heinz ketchup, and other food brands",
  "GIS": "General Mills — makes Cheerios, Häagen-Dazs, and other food brands",
  "K": "Kellanova — makes Pringles, Pop-Tarts, and Kellogg's cereals",
  "CLX": "Clorox — makes Clorox bleach, Burt's Bees, and other household brands",
  "CL": "Colgate-Palmolive — makes Colgate toothpaste and other personal care products",
  "EL": "Estée Lauder — makes luxury cosmetics and skincare brands",
  "ULTA": "Ulta Beauty — the largest US specialty beauty retailer",
  "ETSY": "Etsy — online marketplace for handmade and vintage goods",
  "W": "Wayfair — online home furnishings and décor retailer",
  "CHWY": "Chewy — online pet food and supplies retailer",
  "PTON": "Peloton — makes connected exercise bikes and treadmills",
  "BYND": "Beyond Meat — makes plant-based meat alternatives",
  "WING": "Wingstop — fast-casual chicken wings restaurant chain",
  "CMG": "Chipotle Mexican Grill — fast-casual Mexican restaurant chain",
  "DPZ": "Domino's Pizza — the world's largest pizza delivery chain",
  "YUM": "Yum! Brands — owns KFC, Pizza Hut, and Taco Bell",
  "QSR": "Restaurant Brands International — owns Burger King, Tim Hortons, and Popeyes",
  "WEN": "Wendy's — US fast-food burger chain",
  "DKNG": "DraftKings — online sports betting and daily fantasy sports platform",
  "MGM": "MGM Resorts — operates casinos and hotels including the Bellagio",
  "CZR": "Caesars Entertainment — operates Caesars, Harrah's, and other casinos",
  "WYNN": "Wynn Resorts — operates luxury casinos in Las Vegas and Macau",
  "LVS": "Las Vegas Sands — operates the Venetian in Las Vegas and major Macau casinos",
  "CCL": "Carnival Corporation — the world's largest cruise line operator",
  "RCL": "Royal Caribbean — the world's second-largest cruise line operator",
  "DAL": "Delta Air Lines — one of the largest US airlines",
  "UAL": "United Airlines — one of the largest US airlines",
  "AAL": "American Airlines — the world's largest airline by fleet size",
  "LUV": "Southwest Airlines — the largest US low-cost carrier",
  "ALK": "Alaska Airlines — major US regional carrier",
  "MAR": "Marriott International — the world's largest hotel chain",
  "HLT": "Hilton Worldwide — one of the largest global hotel chains",
  "H": "Hyatt Hotels — major global luxury hotel operator",
  "ABNB": "Airbnb — operates the world's largest home-sharing rental platform",
  "EXPE": "Expedia — online travel booking platform",
  "BKNG": "Booking Holdings — runs Booking.com, Priceline, and other travel platforms",
  "NCLH": "Norwegian Cruise Line — major cruise line operator",
  "GM": "General Motors — major US automaker",
  "RACE": "Ferrari — makes luxury and Formula 1 sports cars",
  "TM": "Toyota — the world's largest automaker by volume",
  "HMC": "Honda — Japanese automaker and motorcycle manufacturer",
  "STLA": "Stellantis — makes Jeep, Ram, Dodge, Chrysler, Fiat, and Peugeot vehicles",
  "XPEV": "XPeng — Chinese electric vehicle manufacturer",
  "LI": "Li Auto — Chinese electric vehicle manufacturer",
  "ON": "ON Semiconductor — makes power and sensing chips for EVs and industrial use",
  "WOLF": "Wolfspeed — makes silicon carbide chips used in electric vehicles",
  "SMCI": "Super Micro Computer — makes high-performance servers used for AI",
  "DELL": "Dell Technologies — makes PCs, servers, and enterprise storage",
  "HPQ": "HP Inc. — makes personal computers and printers",
  "HPE": "Hewlett Packard Enterprise — makes enterprise servers, storage, and networking",
  "IBM": "IBM — makes mainframes, consulting services, and AI (Watson)",
  "ORCL": "Oracle — makes enterprise database software and cloud services",
  "SAP": "SAP — the world's largest enterprise resource planning (ERP) software company",
  "ADBE": "Adobe — makes Photoshop, Acrobat, and Creative Cloud software",
  "INTU": "Intuit — makes TurboTax, QuickBooks, and Mint financial software",
  "ANSS": "Ansys — makes simulation software used in engineering and product design",
  "CDNS": "Cadence Design Systems — makes chip design (EDA) software",
  "SNPS": "Synopsys — makes chip design tools and software security products",
  "ADSK": "Autodesk — makes AutoCAD and 3D design software",
  "WDAY": "Workday — makes HR and financial management software for enterprises",
  "HUBS": "HubSpot — makes marketing, sales, and CRM software for businesses",
  "ZI": "ZoomInfo — makes B2B sales and marketing intelligence software",
  "GTLB": "GitLab — makes DevOps and software development collaboration tools",
  "PATH": "UiPath — makes robotic process automation (RPA) software",
  "AI": "C3.ai — makes enterprise artificial intelligence software",
  "BBAI": "BigBear.ai — makes AI-powered analytics for defense and intelligence",
  "SOUN": "SoundHound AI — makes voice AI and conversational intelligence technology",
  "IONQ": "IonQ — makes quantum computing hardware and software",
  "RGTI": "Rigetti Computing — makes quantum computing processors",
  "QBTS": "D-Wave Quantum — makes quantum computing systems",
  "RCAT": "Red Cat Holdings — makes drones for defense and security",
  "JOBY": "Joby Aviation — developing electric air taxis",
  "ACHR": "Archer Aviation — developing electric vertical takeoff aircraft",
  "LILM": "Lilium — developing electric jet-powered air taxis",
  "SPCE": "Virgin Galactic — commercial spaceflight and space tourism company",
  "RKLB": "Rocket Lab — launches small satellites and makes spacecraft",
  "ASTR": "Astra Space — makes small satellite launch vehicles",
  "LUNR": "Intuitive Machines — makes lunar landers for NASA missions",
  "RR": "Rolls-Royce — makes aircraft engines and power systems",
  "HII": "Huntington Ingalls Industries — builds US Navy warships and submarines",
  "LDOS": "Leidos — provides IT and engineering services to US defense agencies",
  "SAIC": "SAIC — provides IT and defense solutions to the US government",
  "BAH": "Booz Allen Hamilton — consulting firm specializing in US defense and intelligence",
  "CACI": "CACI International — provides IT and analytics to US defense agencies",
  "DRS": "Leonardo DRS — makes defense electronics and power systems",
  "AXON": "Axon Enterprise — makes Tasers, body cameras, and police software",
  "VRT": "Vertiv Holdings — makes data center power and cooling equipment",
  "EQIX": "Equinix — the world's largest data center and colocation provider",
  "DLR": "Digital Realty — major data center real estate investment trust",
  "AMT": "American Tower — the world's largest cell tower REIT",
  "CCI": "Crown Castle — major US cell tower and fiber network REIT",
  "SBAC": "SBA Communications — US cell tower REIT",
  "GLPI": "Gaming and Leisure Properties — casino real estate investment trust",
  "VICI": "VICI Properties — casino and entertainment real estate investment trust",
  "O": "Realty Income — large retail net-lease REIT paying monthly dividends",
  "SPG": "Simon Property Group — the largest US shopping mall REIT",
  "PSA": "Public Storage — the largest US self-storage REIT",
  "AVB": "AvalonBay Communities — major US apartment REIT",
  "EQR": "Equity Residential — major US apartment REIT",
  "PLD": "Prologis — the world's largest industrial and logistics warehouse REIT",
  "WPC": "W. P. Carey — diversified global net-lease REIT",
  "NNN": "NNN REIT — owns net-leased retail properties",
  "FRT": "Federal Realty Investment Trust — owns retail and mixed-use properties",
  "ARE": "Alexandria Real Estate — owns life science and tech office buildings",
  "HST": "Host Hotels & Resorts — the largest hotel REIT",
  "KIM": "Kimco Realty — owns open-air shopping centers",
  "REG": "Regency Centers — owns grocery-anchored shopping centers",
  "STOR": "STORE Capital — net-lease REIT focused on middle-market companies",
  "WY": "Weyerhaeuser — the largest US timberland REIT and lumber producer",
  "PCH": "PotlatchDeltic — timberland REIT and lumber manufacturer",
  "WELL": "Welltower — the largest healthcare REIT owning senior housing",
  "VTR": "Ventas — major healthcare REIT owning senior housing and medical offices",
  "DOC": "Healthpeak Properties — owns life science buildings and medical offices",
  "MPW": "Medical Properties Trust — owns hospitals and healthcare facilities",
  "UDR": "UDR — owns and operates apartment communities",
  "ESS": "Essex Property Trust — owns apartment communities on the US West Coast",
  "MAA": "Mid-America Apartment Communities — owns apartments in the Sun Belt",
  "CPT": "Camden Property Trust — owns apartment communities across the US"
};
