// Sentiment keyword weights — positive values are bullish signals, negative are bearish
export const BULLISH_KEYWORDS = {
  "beats": 3,
  "beat": 3,
  "record": 2,
  "upgrade": 3,
  "upgraded": 3,
  "raised guidance": 3,
  "raises guidance": 3,
  "acquisition": 2,
  "acquires": 2,
  "acquired": 2,
  "partnership": 2,
  "partners with": 2,
  "breakout": 2,
  "exceeds expectations": 3,
  "exceeded expectations": 3,
  "surpasses": 3,
  "surpassed": 3,
  "outperforms": 2,
  "outperformed": 2,
  "profit": 1,
  "revenue growth": 2,
  "revenue beat": 3,
  "earnings beat": 3,
  "eps beat": 3,
  "strong results": 2,
  "buy rating": 3,
  "buy": 1,
  "bullish": 2,
  "rally": 2,
  "rallies": 2,
  "surge": 2,
  "surges": 2,
  "soars": 2,
  "soar": 2,
  "jumps": 2,
  "jump": 2,
  "climbs": 1,
  "gain": 1,
  "gains": 1,
  "growth": 1,
  "expands": 1,
  "expansion": 1,
  "new high": 2,
  "all-time high": 3,
  "dividend increase": 2,
  "buyback": 2,
  "share buyback": 2,
  "stock buyback": 2,
  "positive outlook": 2,
  "raised price target": 3,
  "price target raised": 3,
  "analyst upgrade": 3,
  "strong buy": 3,
  "overweight": 2,
  "outperform": 2
};

export const BEARISH_KEYWORDS = {
  "misses": -3,
  "miss": -3,
  "missed": -3,
  "downgrade": -3,
  "downgraded": -3,
  "recall": -2,
  "layoffs": -2,
  "layoff": -2,
  "sec investigation": -3,
  "sec probe": -3,
  "guidance cut": -3,
  "cuts guidance": -3,
  "cut guidance": -3,
  "lowered guidance": -3,
  "bankruptcy": -4,
  "bankrupt": -4,
  "lawsuit": -2,
  "litigation": -2,
  "investigation": -2,
  "fraud": -3,
  "fine": -2,
  "penalty": -2,
  "earnings miss": -3,
  "revenue miss": -3,
  "eps miss": -3,
  "below expectations": -3,
  "disappoints": -3,
  "disappointing": -2,
  "sell rating": -3,
  "sell": -1,
  "bearish": -2,
  "decline": -2,
  "declines": -2,
  "drops": -2,
  "drop": -2,
  "falls": -2,
  "fall": -2,
  "plunges": -3,
  "plunge": -3,
  "slumps": -2,
  "slump": -2,
  "loss": -2,
  "losses": -2,
  "negative outlook": -2,
  "lowered price target": -3,
  "price target cut": -3,
  "analyst downgrade": -3,
  "underweight": -2,
  "underperform": -2,
  "warning": -1,
  "concern": -1,
  "risk": -1,
  "headwinds": -2,
  "restructuring": -1,
  "write-down": -2,
  "writedown": -2,
  "impairment": -2
};

// Magnitude modifiers that multiply the base keyword weight
export const MAGNITUDE_MODIFIERS = {
  "significantly": 1.5,
  "sharply": 1.5,
  "unexpected": 1.5,
  "unexpectedly": 1.5,
  "dramatically": 1.5,
  "massively": 1.5,
  "huge": 1.4,
  "major": 1.3,
  "strong": 1.3,
  "strongly": 1.3,
  "slight": 0.5,
  "slightly": 0.5,
  "modest": 0.6,
  "modestly": 0.6,
  "small": 0.5
};

// Minimum absolute aggregate score required to emit a signal
export const SIGNAL_THRESHOLD = 2;

// Maximum age of articles to include (72 hours in milliseconds)
export const MAX_ARTICLE_AGE_MS = 72 * 60 * 60 * 1000;

// Alarm name for periodic refresh
export const REFRESH_ALARM_NAME = "finance-signal-refresh";

// How often to refresh news data (in minutes)
export const REFRESH_INTERVAL_MINUTES = 30;

// chrome.storage.local keys
export const STORAGE_KEYS = {
  LATEST_SIGNALS: "latestSignals",
  LATEST_ARTICLES: "latestArticles",
  FEEDBACK_LOG: "feedbackLog",
  LAST_FETCH_TIME: "lastFetchTime"
};

// Known tickers with plain-language company descriptions for users unfamiliar with companies
export const TICKER_TO_COMPANY = {
  "AAPL": "Apple — makes iPhones, MacBooks, and the App Store",
  "MSFT": "Microsoft — makes Windows, Office, and Azure cloud services",
  "GOOGL": "Alphabet / Google — runs the Google search engine, YouTube, and Google Cloud",
  "GOOG": "Alphabet / Google (Class C) — runs the Google search engine, YouTube, and Google Cloud",
  "AMZN": "Amazon — runs the world's largest online store and AWS cloud infrastructure",
  "NVDA": "Nvidia — designs chips (GPUs) used in AI, gaming, and data centers",
  "META": "Meta — owns Facebook, Instagram, and WhatsApp",
  "TSLA": "Tesla — makes electric vehicles and energy storage systems",
  "BRK.A": "Berkshire Hathaway (Class A) — Warren Buffett's holding company owning many large businesses",
  "BRK.B": "Berkshire Hathaway (Class B) — Warren Buffett's holding company owning many large businesses",
  "LLY": "Eli Lilly — pharmaceutical company known for diabetes and weight-loss drugs",
  "V": "Visa — operates the world's largest electronic payment network",
  "JPM": "JPMorgan Chase — the largest US bank by assets",
  "UNH": "UnitedHealth Group — the largest US health insurance company",
  "XOM": "ExxonMobil — one of the world's largest oil and gas companies",
  "JNJ": "Johnson & Johnson — makes pharmaceuticals, medical devices, and consumer products",
  "WMT": "Walmart — the world's largest retailer by revenue",
  "MA": "Mastercard — operates a global electronic payment network",
  "PG": "Procter & Gamble — makes consumer brands like Tide, Pampers, and Gillette",
  "HD": "Home Depot — the largest US home improvement retailer",
  "CVX": "Chevron — major US oil and gas company",
  "MRK": "Merck — pharmaceutical company known for Keytruda cancer drug",
  "ABBV": "AbbVie — pharmaceutical company known for Humira and Botox",
  "KO": "Coca-Cola — the world's largest beverage company",
  "AVGO": "Broadcom — designs semiconductor chips for data centers and networking",
  "PEP": "PepsiCo — makes Pepsi beverages, Lay's chips, and Quaker foods",
  "COST": "Costco — membership-based warehouse retailer",
  "TMO": "Thermo Fisher Scientific — makes instruments and reagents for scientific research",
  "MCD": "McDonald's — the world's largest fast food chain",
  "CSCO": "Cisco Systems — makes networking hardware and software for enterprises",
  "ACN": "Accenture — global consulting and IT services firm",
  "ABT": "Abbott Laboratories — makes medical devices, diagnostics, and nutrition products",
  "DHR": "Danaher — makes precision instruments for life sciences and diagnostics",
  "LIN": "Linde — the world's largest industrial gases company",
  "NKE": "Nike — the world's largest athletic footwear and apparel brand",
  "TXN": "Texas Instruments — makes analog and embedded semiconductors",
  "PM": "Philip Morris International — makes cigarettes and tobacco alternatives globally",
  "VZ": "Verizon — one of the two largest US mobile carriers",
  "DIS": "Walt Disney — owns Disney Parks, ESPN, Pixar, Marvel, and Star Wars",
  "NEE": "NextEra Energy — the world's largest producer of solar and wind energy",
  "MS": "Morgan Stanley — major US investment bank and wealth manager",
  "UNP": "Union Pacific — operates the largest US freight railroad",
  "RTX": "RTX (Raytheon) — makes aerospace and defense systems",
  "HON": "Honeywell — makes industrial automation, aerospace, and building technology",
  "BMY": "Bristol-Myers Squibb — pharmaceutical company making cancer and cardiovascular drugs",
  "QCOM": "Qualcomm — designs chips used in most Android smartphones",
  "AMGN": "Amgen — biotech company making drugs for cancer, bone disease, and inflammation",
  "T": "AT&T — one of the two largest US mobile carriers",
  "INTC": "Intel — largest US maker of PC and server processors",
  "AMD": "AMD — makes CPUs and GPUs competing with Intel and Nvidia",
  "PYPL": "PayPal — runs the PayPal and Venmo digital payment platforms",
  "CRM": "Salesforce — the world's largest customer relationship management software company",
  "NOW": "ServiceNow — makes cloud software for IT and business workflow automation",
  "UBER": "Uber — runs the world's largest ride-sharing and food delivery platforms",
  "ABNB": "Airbnb — operates the world's largest home-sharing rental platform",
  "SNAP": "Snap — makes the Snapchat photo/video messaging app",
  "SPOT": "Spotify — the world's largest music and podcast streaming service",
  "NFLX": "Netflix — the world's largest video streaming service",
  "BA": "Boeing — makes commercial aircraft and defense systems",
  "CAT": "Caterpillar — makes heavy construction and mining equipment",
  "GS": "Goldman Sachs — major US investment bank",
  "BKNG": "Booking Holdings — runs Booking.com, Priceline, and other travel platforms",
  "SBUX": "Starbucks — the world's largest coffeehouse chain",
  "GE": "GE Aerospace — makes jet engines and aviation systems",
  "F": "Ford — major US automaker",
  "GM": "General Motors — major US automaker",
  "PFE": "Pfizer — pharmaceutical company known for COVID vaccines and cancer drugs",
  "AZN": "AstraZeneca — UK-Swedish pharmaceutical company",
  "TSM": "TSMC — the world's largest contract chip manufacturer (makes chips for Apple and Nvidia)",
  "SHOP": "Shopify — e-commerce platform used by small and mid-size businesses",
  "SQ": "Block (formerly Square) — makes payment hardware and the Cash App",
  "COIN": "Coinbase — the largest US cryptocurrency exchange",
  "PLTR": "Palantir — makes data analytics software for governments and enterprises",
  "ARM": "Arm Holdings — designs CPU architectures used in nearly all smartphones",
  "ASML": "ASML — makes the machines that print chips; critical to the semiconductor supply chain",
  "MU": "Micron Technology — makes DRAM and NAND memory chips",
  "WFC": "Wells Fargo — one of the four largest US banks",
  "BAC": "Bank of America — one of the four largest US banks",
  "C": "Citigroup — one of the four largest US banks",
  "BX": "Blackstone — the world's largest alternative asset manager",
  "SPGI": "S&P Global — runs the S&P 500 index and provides financial data",
  "MCO": "Moody's — provides credit ratings and financial intelligence",
  "ICE": "Intercontinental Exchange — operates the New York Stock Exchange",
  "CME": "CME Group — operates the world's largest derivatives exchange",
  "PANW": "Palo Alto Networks — makes enterprise cybersecurity products",
  "CRWD": "CrowdStrike — makes cloud-based endpoint cybersecurity software",
  "SNOW": "Snowflake — makes cloud data warehousing software",
  "DDOG": "Datadog — makes cloud monitoring and observability software",
  "ZM": "Zoom — makes the Zoom video conferencing platform",
  "OKTA": "Okta — makes identity and access management software",
  "NET": "Cloudflare — runs a global content delivery and security network",
  "MDB": "MongoDB — makes a widely used open-source document database",
  "ESTC": "Elastic — makes Elasticsearch, used for search and log analytics",
  "RH": "RH (Restoration Hardware) — luxury home furnishings retailer",
  "LULU": "Lululemon — premium athletic apparel brand",
  "TGT": "Target — major US discount retailer",
  "LOW": "Lowe's — the second-largest US home improvement retailer",
  "DE": "John Deere — makes farm equipment and precision agriculture technology",
  "LMT": "Lockheed Martin — makes F-35 jets and other defense systems",
  "NOC": "Northrop Grumman — makes B-21 bombers and other defense systems",
  "GD": "General Dynamics — makes Gulfstream jets and defense systems",
  "OXY": "Occidental Petroleum — US oil and gas company",
  "COP": "ConocoPhillips — major US oil and gas exploration company",
  "SLB": "SLB (Schlumberger) — the world's largest oilfield services company",
  "HAL": "Halliburton — major oilfield services company"
};
